#pragma once
#define STEEL_MOUSE_BUTTON_1         0
#define STEEL_MOUSE_BUTTON_2         1
#define STEEL_MOUSE_BUTTON_3         2
#define STEEL_MOUSE_BUTTON_4         3
#define STEEL_MOUSE_BUTTON_5         4
#define STEEL_MOUSE_BUTTON_6         5
#define STEEL_MOUSE_BUTTON_7         6
#define STEEL_MOUSE_BUTTON_8         7
#define STEEL_MOUSE_BUTTON_LAST      STEEL_MOUSE_BUTTON_8
#define STEEL_MOUSE_BUTTON_LEFT      STEEL_MOUSE_BUTTON_1
#define STEEL_MOUSE_BUTTON_RIGHT     STEEL_MOUSE_BUTTON_2
#define STEEL_MOUSE_BUTTON_MIDDLE    STEEL_MOUSE_BUTTON_3